# Generated by Django 3.2.4 on 2021-06-10 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('image2', models.ImageField(upload_to='', verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image 3')),
            ],
            options={
                'verbose_name': 'Example Model',
                'verbose_name_plural': 'Example Models',
            },
        ),
        migrations.CreateModel(
            name='ExampleModelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.examplemodel')),
            ],
        ),
        migrations.CreateModel(
            name='AnotherModalImagesExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.examplemodel')),
            ],
        ),
    ]
