# Generated by Django 3.2.4 on 2021-06-10 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackedExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Example')),
                ('text', models.TextField(verbose_name='Text')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.examplemodel')),
            ],
        ),
    ]
