# Generated by Django 3.2.4 on 2021-06-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_application', '0002_alter_examplemodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examplemodel',
            options={'verbose_name': 'Example Model', 'verbose_name_plural': 'Example Models'},
        ),
        migrations.CreateModel(
            name='ExampleModelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.examplemodel')),
            ],
        ),
    ]
