# Generated by Django 4.1 on 2022-09-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_application', '0002_stackedexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestNonRequired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Example Model',
                'verbose_name_plural': 'Example Models',
            },
        ),
        migrations.RemoveField(
            model_name='examplemodelimage',
            name='example',
        ),
        migrations.RemoveField(
            model_name='stackedexample',
            name='example',
        ),
        migrations.DeleteModel(
            name='AnotherModalImagesExample',
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.DeleteModel(
            name='ExampleModelImage',
        ),
        migrations.DeleteModel(
            name='StackedExample',
        ),
    ]
