# Generated by Django 3.2.4 on 2021-06-10 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_application', '0003_auto_20210606_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherModalImagesExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.examplemodel')),
            ],
        ),
    ]
