# Generated by Django 4.1 on 2022-09-09 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_application', '0008_testrequiredtabularinline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Test Non Required Tabular Inline',
            },
        ),
        migrations.CreateModel(
            name='InlineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='demo_application.inline')),
            ],
        ),
    ]
