# Generated by Django 4.1 on 2022-09-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_application', '0009_inline_inlineitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inline',
            options={'verbose_name': 'Test With Inline'},
        ),
    ]
