# Generated by Django 4.1 on 2022-10-16 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_application', '0010_alter_inline_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Test Customized Inline',
            },
        ),
        migrations.CreateModel(
            name='CustomInlineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='demo_application.custominline')),
            ],
        ),
    ]
