# Generated by Django 5.2 on 2025-04-23 01:20

from django.db import migrations, models

import image_uploader_widget.postgres.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestWithArrayField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    image_uploader_widget.postgres.fields.ImageListField(
                        base_field=models.ImageField(
                            max_length=150, upload_to="admin_test"
                        ),
                        blank=True,
                        max_length=None,
                        null=True,
                        size=None,
                        upload_to="admin_test",
                    ),
                ),
            ],
            options={
                "verbose_name": "(Array Field) Default",
            },
        ),
    ]
