# Generated by Django 5.0 on 2023-12-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_orderedinline_orderedinlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedinlineitem',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Order'),
        ),
    ]
