# Generated by Django 5.0.2 on 2024-02-27 02:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_orderedinlineitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestWithArrayField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), size=None)),
            ],
            options={
                'verbose_name': 'Test With Array Field',
            },
        ),
    ]
